### ISSUE TITLE
Files organization

### ISSUE THREAD

**Issue by raphaeltimbo** [vibrationtoolbox/vibration_toolbox#5]
Joseph,
I think the file vtoolbox.py is getting large (675 lines now) and I am having trouble to find things inside the code. 
I was thinking about creating different files and then I would import those in the vtoolbox.py.
Ex.: create a free_response.py with the functions for free response. Inside vtoolbox.py we would have from free_response import sdof_free response, sdof... 
I think this would help to organize things.
I don't know in which way the files could be named. I was thinking about something related to the chapters from Inman. 
What do you think about that?

**Comment by josephcslater** [comment]
Frankly I'd like to move away from that book. Keep in mind, I wrote the software for him for $1000 23 years ago. I'm still doing the job, lol. I'd like it to be text independent, so let's not organize as per the book, but simply by function. 

It might be easiest to have a single .py file that they all call that sets up the imports (scipy, etc.), separating them into files will be fine. I can later organize them so import vtoolbox imports all of them. separating files doesn't change that in python. 

The numerical stuff is fine, but in reality dead. Nobody would use either of those methods today. Much better integrators abound. The integrator built into scipy is better. Why expend time learning an old method that works poorly? It's worthwhile for a numerical methods class, but this is about understanding the physics of vibration and how to do analysis to drive engineering decisions. That's much more critical. Thus the need for sliders in the notebooks so that one can learn to get a feel for parametric sensitivities.

**Comment by raphaeltimbo** [comment]
Regarding the organization of files, I was thinking that we could have a `__init__.py` file inside the pvtoolbox directory. Inside this file we could write -> `from . import free_response as free`. If we use -> `import pvtoolbox as pv` inside the notebook, functions inside free_response.py will be available using pv.free. (e.g.: `pv.free.sdof_free_response()` to call sdof_free_response).

**Comment by josephcslater** [comment]
That's too convoluted for the user in my opinion.  I would only want separate .py files to make it easier a for use to edit.  Can we not make it one "." with everything after that? Having a complex structure for users is unnecessary and cumbersome. 

That said, I don't want p in the import, etc.  I just want the name in usage to be vibration toolbox, or perhaps even renamed.  If the user is in Python, Python is already clear.  

I don't have a good answer yet, but these are things to keep in mind.

**Comment by raphaeltimbo** [comment]
You are right. I am still trying to understand python import.. Maybe later we can find a way to organize this. For now I am going to keep using the vtoolbox.py file.

**Comment by josephcslater** [comment]
Use the .py file, but let's use separate ipynb  files because they merge so poorly.  

I did have the thought of perhaps pulling out the sdof stuff, chapters 1-3, which can also be tools for later on to some degree.  That's a more logical break around a larger chunk.

**Comment by raphaeltimbo** [comment]
Regarding the ipynb files, I was looking at that and the biggest problem are the outputs from the notebooks. For version control we can word around this by using the 'clear outputs' from the notebook or better:
https://github.com/kynan/nbstripout

**Comment by josephcslater** [comment]
This is a good plan. It's what I did with my course notes.

**Comment by josephcslater** [comment]
> On Jul 23, 2016, at 9:25 PM, raphaeltimbo notifications@github.com wrote:
> 
> Regarding the ipynb files, I was looking at that and the biggest problem are the outputs from the notebooks. For version control we can word around this by using the 'clear outputs' from the notebook or better:
> https://github.com/kynan/nbstripout https://github.com/kynan/nbstripoutI have implemented this in .gitattributes. I don't know if you need to do anything on your machine to make it work locally for you. 

Best Regards- Joe

**Comment by josephcslater** [comment]
Please sync and take a look at the new mods. 
I renamed vtoolbox.py to sdof.py as a way to separate them from what will be less educational and more utilitarian codes. Renaming functions may now make sense as sdof in function names will appear redundant. This should make the usage a bit cleaner.

**Comment by josephcslater** [comment]
pip install works. Whether the package works... well, that's why it's beta. 

https://pypi.python.org/pypi/VibrationToolbox/0.5b0

**Comment by raphaeltimbo** [comment]
I am closing this one since now I think the project has a defined structure for the files/modules.
